### ISSUE TITLE
Use dash instead of dot in module filename (aka myanmar-phonenumber.js)

### ISSUE THREAD

**Issue by trhura** [kaungmyatlwin/myanmar-phonenumber-js#1]
I am trying to use your package in one of my react native application and running into the problem below. 

> error: bundling failed: Error: While trying to resolve module `myanmar-phonenumber` from file `/Users/thurahlaing/Devel/.../src/screens/signin/First.js`, the package `/Users/thurahlaing/Devel/.../node_modules/myanmar-phonenumber/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/thurahlaing/Devel/.../node_modules/myanmar-phonenumber/myanmar-phonenumber.js`. Indeed, none of these files exist:

>`/Users/thurahlaing/Devel/.../node_modules/myanmar-phonenumber/myanmar-phonenumber.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`

>  `/Users/thurahlaing/Devel/.../node_modules/myanmar-phonenumber/myanmar-phonenumber.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`

It should be resolved if you change the filename to have the same name as package name.

**Comment by kaungmyatlwin** [comment]
Right. It's a problem that I overlooked. Changed file name in d47bf19709859dc00157d99870786d009747d7c5.
