### ISSUE TITLE
Not working with empty string

### ISSUE THREAD

**Issue by kaungmyathan22** [kaungmyatlwin/myanmar-phonenumber-js#9]
`let phone=""`
when calling isValidMMPhoneNumber(phone) return nothing.
and 
`let phone=" "`;
when calling isValidMMPhoneNumber(phone) return false.

**Comment by kaungmyatlwin** [comment]
This is intended behavior. Do you have a better suggestion?

**Comment by kaungmyatlwin** [comment]
Ok coming back to the issue, I see the point you were making. I apologize.

Will release the new version with empty string check to return `Boolean`.

**Comment by kaungmyatlwin** [comment]
@kaungmyathan22 For `phone = '  '`, we now will throw an error `Phone number is empty.`. I don't think it would make sense to `return false` for such an empty string.

**Comment by kaungmyatlwin** [comment]
Fix provided in https://github.com/kaungmyatlwin/myanmar-phonenumber/commit/1975dd65abebb2fc24751f10a6e002421dffc5a9.
